### ISSUE TITLE
Changing Duke Class Name

### ISSUE THREAD

**Issue by ryantanlien** [nus-cs2103-AY2122S2/forum#9] opened 2022-01-19 09:32 UTC
Is it alright to change the Duke.java name to something more appropriate to our chat bot? Or do we keep it as Duke.java because of marking purposes or some such?

**Comment by zhongfu** [comment] 2022-01-19 09:35
duplicate of #3: yes, it's fine

**Closed** 2022-01-19 09:36 UTC
Labels: type-Question :thinking:
